# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.
If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [137]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [138]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [139]:
a = np.zeros(10)
a[4]=5
a

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [140]:
a = np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [141]:
a = np.random.random((9)) * 8
a.reshape((3, 3))

array([[1.18670044, 2.84777602, 4.06205388],
       [7.08517834, 4.83587553, 0.99092694],
       [0.35323353, 4.22261519, 4.67786792]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [142]:
a = np.array([1,2,0,0,4,0])
a.nonzero()

(array([0, 1, 4], dtype=int64),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [143]:
a = np.array([[[1,0,0],[0,1,0],[0,0,1]]])
a

array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [144]:
a = np.random.random((3,3)) 
a

array([[0.02806906, 0.393037  , 0.40566079],
       [0.20128773, 0.45409173, 0.34835915],
       [0.91016925, 0.81129493, 0.52756869]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [145]:
a = np.random.random((10,10)) 
print(a.min(), a.max())

0.003791712497880795 0.9866523872117797


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [146]:
a = np.random.random(30)
a.mean()

0.5158403614179385

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [204]:
c = np.diag((1,2,3,4), k=-1)
print(c)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [148]:
import seaborn as sns
a = np.random.random((5,5)) * 100
a = (a - np.mean(a)) / np.std(a)
print(a)
#sns.histplot(data = a, legend = False, bins = 100)

[[ 1.10260244 -0.72661657  0.54946074  1.16871464  1.45018932]
 [ 0.28222634 -1.03077947  1.29020641  0.76204288 -1.33053105]
 [-0.95177882 -0.02706228  0.70306264  0.74822359  0.25729306]
 [-1.16796669 -0.16035276  1.19676226 -0.39887329 -0.27413876]
 [-0.46672493 -1.56767721 -0.21232481  1.10622898 -2.30218662]]


#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [160]:
a = np.random.randint(0,10,5)
b = np.random.randint(0,10,5)
print(a,b)
np.intersect1d(a,b)

[1 2 8 0 5] [3 1 2 5 9]


array([1, 2, 5])

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [161]:
a = np.random.randint(0,10,10)
a.sort()
a

array([1, 2, 2, 2, 4, 5, 6, 8, 8, 9])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [244]:
a = np.random.randint(0,10,5)
print(a)
s = list(np.where(a == a.max()))
for i in s: 
    a[i]=0
print(a)

[7 7 7 5 1]
[0 0 0 5 1]


#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [338]:
a = np.random.randint(5, size=(4, 4))
a
listMeans = []
for i in range(0,4):
    listMeans.append(np.mean(a[i], keepdims=True))
print(a)
print(listMeans)

[[1 4 0 4]
 [3 1 2 1]
 [1 1 2 1]
 [4 4 3 0]]
[array([2.25]), array([1.75]), array([1.25]), array([2.75])]


In [345]:
for i in range(0,4):
    a[i] = a[i] - listMeans[0]
print(a)
a = a.astype(numpy.float32)
print(listMeans)

[[-3.   -1.   -4.   -1.  ]
 [-1.75 -2.75 -1.75 -2.75]
 [-2.5  -2.5  -1.5  -2.5 ]
 [-1.25 -1.25 -2.25 -4.25]]
[array([2.25]), array([1.75]), array([1.25]), array([2.75])]


In [346]:
#b = np.mean(a[1], keepdims=True)
#print(a)
for i in range(0,4):
    a[i] = a[i] - np.mean(a[i], keepdims=True)
    #print(a[i])
print(a)

[[-0.75  1.25 -1.75  1.25]
 [ 0.5  -0.5   0.5  -0.5 ]
 [-0.25 -0.25  0.75 -0.25]
 [ 1.    1.    0.   -2.  ]]


#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [418]:
Z = np.arange(25)
np.random.shuffle(Z)
n = 5
a = np.argsort(Z, axis=-1, kind='mergesort', order=None)
Z2 = Z.copy()
Z2.sort()
print(Z)
print(a)
print(Z2)
Z2[-n]

[15 23 21 14 17  7 13 22 10  1 20 11  4  5 24 12  9  2 18 19  0  3  8  6
 16]
[20  9 17 21 12 13 23  5 22 16  8 11 15  6  3  0 24  4 18 19 10  2  7  1
 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


20

In [411]:
Z2 = Z.copy()
Z2.sort()
print(Z2)

[ 2  5 13  8 12  0 17  4  6  1  7 11  3 14  9 18 10 19 15 16]
[ 5  9  0 12  7  1  8 10  3 14 16 11  4  2 13 18 19  6 15 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [410]:
Z2 = Z.copy()
Z2.sort()
print(Z2)
print(Z[-n])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
6


In [404]:
a = np.argsort(Z, axis=-1, kind='mergesort', order=None)
n_index = a[-n]
Z[n_index]

3

In [386]:
a.sort()
a
a[-n]

15

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [420]:
a = np.random.randint(5, size=(5,3))
a

array([[1, 3, 4],
       [4, 3, 3],
       [3, 2, 1],
       [2, 0, 4],
       [3, 1, 2]])

In [421]:
np.where(a > 4, a, a**2)

array([[ 1,  9, 16],
       [16,  9,  9],
       [ 9,  4,  1],
       [ 4,  0, 16],
       [ 9,  1,  4]])